import type { L, Product, SizeOption } from "./types";

const SIZE_TIERS = {
  s: {
    label: { en: "Sling", fr: "Jeune" } satisfies L,
    sizeMinInches: 0.125,
    sizeMaxInches: 0.75,
  },
  j: {
    label: { en: "Juvenile", fr: "Juvénile" } satisfies L,
    sizeMinInches: 0.875,
    sizeMaxInches: 1.75,
  },
  u: {
    label: { en: "Sub-adult", fr: "Sub-adulte" } satisfies L,
    sizeMinInches: 2,
    sizeMaxInches: 3.5,
  },
} as const;

function sz(key: keyof typeof SIZE_TIERS, price: number, stock: number): SizeOption {
  const tier = SIZE_TIERS[key];
  return { id: key, ...tier, price, stock };
}

export const PRODUCTS: Product[] = [
  {
    id: "gpulchra",
    slug: "grammostola-pulchra-brazilian-black",
    scientific: "Grammostola pulchra",
    common: { en: "Brazilian Black", fr: "Mygale noire du Brésil" },
    genus: "Grammostola",
    experience: "beginner",
    type: "terrestrial",
    temperament: "docile",
    featured: true,
    rating: 4.9,
    reviews: 128,
    hue: 220,
    accent: "#3a3a44",
    sizes: [
      sz("s", 65, 8),
      sz("j", 120, 5),
      sz("u", 240, 2),
    ],
    adultSize: { en: "15–18 cm", fr: "15–18 cm" },
    growth: { en: "Slow", fr: "Lente" },
    origin: { en: "Southern Brazil, Uruguay", fr: "Sud du Brésil, Uruguay" },
    lifespan: { en: "20–30 years", fr: "20–30 ans" },
    humidity: "60–70%",
    temperature: "22–26°C",
    enclosure: { en: "Terrestrial, dry substrate, water dish", fr: "Terrestre, substrat sec, abreuvoir" },
    diet: { en: "Crickets, roaches", fr: "Grillons, blattes" },
    description: {
      en: "The 'velvet jet' of the hobby — a glossy, all-black terrestrial that is famously calm and forgiving. Slow-growing but worth every molt, it's one of the best display tarantulas you can keep.",
      fr: "Le « velours noir » du loisir — une terrestre lustrée entièrement noire, réputée calme et tolérante. À croissance lente mais elle vaut chaque mue : l'une des meilleures mygales de présentation.",
    },
    careGuide: "beginner-setup",
    arrived: "2026-05-20",
  },
  {
    id: "gpulchripes",
    slug: "grammostola-pulchripes-chaco-golden-knee",
    scientific: "Grammostola pulchripes",
    common: { en: "Chaco Golden Knee", fr: "Genou doré du Chaco" },
    genus: "Grammostola",
    experience: "beginner",
    type: "terrestrial",
    temperament: "docile",
    featured: true,
    rating: 4.9,
    reviews: 96,
    hue: 42,
    accent: "#b8893a",
    sizes: [
      sz("s", 30, 14),
      sz("j", 60, 9),
      sz("u", 130, 3),
    ],
    adultSize: { en: "18–21 cm", fr: "18–21 cm" },
    growth: { en: "Medium", fr: "Moyenne" },
    origin: { en: "Paraguay, Argentina", fr: "Paraguay, Argentine" },
    lifespan: { en: "20–25 years", fr: "20–25 ans" },
    humidity: "60–70%",
    temperature: "22–27°C",
    enclosure: { en: "Terrestrial, dry substrate, water dish", fr: "Terrestre, substrat sec, abreuvoir" },
    diet: { en: "Crickets, roaches", fr: "Grillons, blattes" },
    description: {
      en: "A big, gentle giant with golden striping on its legs. Hardy, docile and a great eater — the textbook first tarantula that grows into an impressive showpiece.",
      fr: "Un grand géant doux orné de rayures dorées sur les pattes. Robuste, docile et bonne mangeuse — la première mygale par excellence qui devient une pièce impressionnante.",
    },
    careGuide: "beginner-setup",
    arrived: "2026-05-18",
  },
  {
    id: "bhamorii",
    slug: "brachypelma-hamorii-mexican-red-knee",
    scientific: "Brachypelma hamorii",
    common: { en: "Mexican Red Knee", fr: "Genou rouge du Mexique" },
    genus: "Brachypelma",
    experience: "beginner",
    type: "terrestrial",
    temperament: "docile",
    featured: true,
    rating: 5.0,
    reviews: 211,
    hue: 12,
    accent: "#c0492f",
    sizes: [
      sz("s", 45, 10),
      sz("j", 95, 6),
      sz("u", 200, 2),
    ],
    adultSize: { en: "13–15 cm", fr: "13–15 cm" },
    growth: { en: "Slow", fr: "Lente" },
    origin: { en: "Pacific coast of Mexico", fr: "Côte pacifique du Mexique" },
    lifespan: { en: "25–30 years", fr: "25–30 ans" },
    humidity: "60–65%",
    temperature: "22–27°C",
    enclosure: { en: "Terrestrial, dry substrate, water dish", fr: "Terrestre, substrat sec, abreuvoir" },
    diet: { en: "Crickets, roaches", fr: "Grillons, blattes" },
    description: {
      en: "The icon. Striking orange-red knees, an unhurried temperament and a multi-decade lifespan make this the most recognizable tarantula in the world — and a stellar beginner.",
      fr: "L'icône. Des genoux orange-rouge éclatants, un tempérament posé et une longévité de plusieurs décennies en font la mygale la plus reconnaissable au monde — et une excellente débutante.",
    },
    careGuide: "beginner-setup",
    arrived: "2026-05-25",
  },
  {
    id: "talbopilosus",
    slug: "tliltocatl-albopilosus-curly-hair",
    scientific: "Tliltocatl albopilosus",
    common: { en: "Honduran Curly Hair", fr: "Mygale frisée du Honduras" },
    genus: "Tliltocatl",
    experience: "beginner",
    type: "terrestrial",
    temperament: "docile",
    rating: 4.8,
    reviews: 87,
    hue: 30,
    accent: "#7a5a3a",
    sizes: [
      sz("s", 25, 20),
      sz("j", 50, 11),
    ],
    adultSize: { en: "13–15 cm", fr: "13–15 cm" },
    growth: { en: "Medium-fast", fr: "Moyenne-rapide" },
    origin: { en: "Central America", fr: "Amérique centrale" },
    lifespan: { en: "8–10 (M) / 20+ (F)", fr: "8–10 (M) / 20+ (F)" },
    humidity: "65–70%",
    temperature: "22–27°C",
    enclosure: { en: "Terrestrial, slightly moist substrate", fr: "Terrestre, substrat légèrement humide" },
    diet: { en: "Crickets, roaches", fr: "Grillons, blattes" },
    description: {
      en: "Covered in long, curling golden hairs, this bombproof terrestrial is hardy, hungry and supremely easy. Arguably the single best beginner tarantula for value.",
      fr: "Couverte de longs poils dorés bouclés, cette terrestre increvable est robuste, gourmande et d'une facilité absolue. Sans doute la meilleure mygale débutante côté rapport qualité-prix.",
    },
    careGuide: "beginner-setup",
    arrived: "2026-05-12",
  },
  {
    id: "achalcodes",
    slug: "aphonopelma-chalcodes-arizona-blonde",
    scientific: "Aphonopelma chalcodes",
    common: { en: "Arizona Blonde", fr: "Blonde de l'Arizona" },
    genus: "Aphonopelma",
    experience: "beginner",
    type: "terrestrial",
    temperament: "docile",
    rating: 4.7,
    reviews: 54,
    hue: 38,
    accent: "#c9a86a",
    sizes: [
      sz("s", 40, 7),
      sz("j", 80, 4),
    ],
    adultSize: { en: "12–14 cm", fr: "12–14 cm" },
    growth: { en: "Very slow", fr: "Très lente" },
    origin: { en: "Arizona, USA", fr: "Arizona, É.-U." },
    lifespan: { en: "20–30 years", fr: "20–30 ans" },
    humidity: "55–60%",
    temperature: "24–29°C",
    enclosure: { en: "Terrestrial, dry desert substrate", fr: "Terrestre, substrat désertique sec" },
    diet: { en: "Crickets, roaches", fr: "Grillons, blattes" },
    description: {
      en: "A calm desert dweller with a soft blonde carapace. Extremely low-maintenance and tolerant — perfect for keepers who want a hands-off, long-lived spider.",
      fr: "Une habitante calme du désert au céphalothorax blond. Extrêmement peu exigeante et tolérante — parfaite pour qui veut une mygale longévive et sans tracas.",
    },
    careGuide: "beginner-setup",
    arrived: "2026-04-30",
  },
  {
    id: "cversicolor",
    slug: "caribena-versicolor-antilles-pinktoe",
    scientific: "Caribena versicolor",
    common: { en: "Antilles Pinktoe", fr: "Pattes roses des Antilles" },
    genus: "Caribena",
    experience: "intermediate",
    type: "arboreal",
    temperament: "skittish",
    featured: true,
    newArrival: true,
    rating: 4.8,
    reviews: 73,
    hue: 265,
    accent: "#6c5bbf",
    sizes: [
      sz("s", 45, 12),
      sz("j", 90, 5),
    ],
    adultSize: { en: "12–15 cm", fr: "12–15 cm" },
    growth: { en: "Medium-fast", fr: "Moyenne-rapide" },
    origin: { en: "Martinique, Lesser Antilles", fr: "Martinique, Petites Antilles" },
    lifespan: { en: "10–12 years (F)", fr: "10–12 ans (F)" },
    humidity: "70–80%",
    temperature: "24–28°C",
    enclosure: { en: "Arboreal, vertical, cross-ventilated", fr: "Arboricole, vertical, ventilé" },
    diet: { en: "Crickets, flying insects", fr: "Grillons, insectes volants" },
    description: {
      en: "Slings glow electric blue and mature into a metallic green, red and violet masterpiece. A fast, flighty arboreal that rewards good ventilation — a true showstopper.",
      fr: "Les jeunes brillent d'un bleu électrique et deviennent un chef-d'œuvre vert métallique, rouge et violet. Une arboricole vive qui aime une bonne ventilation — un spectacle absolu.",
    },
    careGuide: "arboreal-setup",
    arrived: "2026-05-28",
  },
  {
    id: "aavicularia",
    slug: "avicularia-avicularia-pinktoe",
    scientific: "Avicularia avicularia",
    common: { en: "Common Pinktoe", fr: "Pattes roses commune" },
    genus: "Avicularia",
    experience: "intermediate",
    type: "arboreal",
    temperament: "docile",
    rating: 4.6,
    reviews: 61,
    hue: 330,
    accent: "#a85b7a",
    sizes: [
      sz("s", 35, 9),
      sz("j", 70, 6),
    ],
    adultSize: { en: "11–13 cm", fr: "11–13 cm" },
    growth: { en: "Medium", fr: "Moyenne" },
    origin: { en: "Northern South America", fr: "Nord de l'Amérique du Sud" },
    lifespan: { en: "10–12 years (F)", fr: "10–12 ans (F)" },
    humidity: "70–80%",
    temperature: "24–28°C",
    enclosure: { en: "Arboreal, vertical, cross-ventilated", fr: "Arboricole, vertical, ventilé" },
    diet: { en: "Crickets, flying insects", fr: "Grillons, insectes volants" },
    description: {
      en: "A fuzzy, dark arboreal with signature pink toe tips. Generally docile and a great entry point to keeping tree-dwelling tarantulas.",
      fr: "Une arboricole sombre et duveteuse aux extrémités roses caractéristiques. Généralement docile et une excellente porte d'entrée vers les mygales arboricoles.",
    },
    careGuide: "arboreal-setup",
    arrived: "2026-04-22",
  },
  {
    id: "ccyaneopubescens",
    slug: "chromatopelma-cyaneopubescens-gbb",
    scientific: "Chromatopelma cyaneopubescens",
    common: { en: "Green Bottle Blue (GBB)", fr: "Bouteille verte bleue (GBB)" },
    genus: "Chromatopelma",
    experience: "beginner",
    type: "terrestrial",
    temperament: "skittish",
    featured: true,
    rating: 4.9,
    reviews: 142,
    hue: 175,
    accent: "#2bb39a",
    sizes: [
      sz("s", 35, 16),
      sz("j", 70, 8),
      sz("u", 140, 3),
    ],
    adultSize: { en: "13–15 cm", fr: "13–15 cm" },
    growth: { en: "Medium-fast", fr: "Moyenne-rapide" },
    origin: { en: "Paraguaná, Venezuela", fr: "Paraguaná, Venezuela" },
    lifespan: { en: "12–14 years (F)", fr: "12–14 ans (F)" },
    humidity: "55–65%",
    temperature: "24–28°C",
    enclosure: { en: "Terrestrial, dry, lots of anchor points", fr: "Terrestre, sec, nombreux points d'ancrage" },
    diet: { en: "Crickets, roaches", fr: "Grillons, blattes" },
    description: {
      en: "Metallic blue legs, a green carapace and a flame-orange abdomen — and a prolific webber that turns its enclosure into art. Hardy enough for beginners, gorgeous enough for everyone.",
      fr: "Pattes bleu métallique, céphalothorax vert et abdomen orange flamboyant — une tisseuse prolifique qui transforme son enclos en œuvre d'art. Assez robuste pour débuter, assez superbe pour tous.",
    },
    careGuide: "beginner-setup",
    arrived: "2026-05-26",
  },
  {
    id: "tvagans",
    slug: "tliltocatl-vagans-mexican-red-rump",
    scientific: "Tliltocatl vagans",
    common: { en: "Mexican Red Rump", fr: "Croupe rouge du Mexique" },
    genus: "Tliltocatl",
    experience: "beginner",
    type: "terrestrial",
    temperament: "skittish",
    rating: 4.6,
    reviews: 49,
    hue: 0,
    accent: "#8c2f2f",
    sizes: [
      sz("s", 25, 13),
      sz("j", 55, 7),
    ],
    adultSize: { en: "13–15 cm", fr: "13–15 cm" },
    growth: { en: "Medium", fr: "Moyenne" },
    origin: { en: "Mexico, Central America", fr: "Mexique, Amérique centrale" },
    lifespan: { en: "15+ years (F)", fr: "15+ ans (F)" },
    humidity: "60–70%",
    temperature: "22–27°C",
    enclosure: { en: "Terrestrial, deep substrate to burrow", fr: "Terrestre, substrat profond pour terrier" },
    diet: { en: "Crickets, roaches", fr: "Grillons, blattes" },
    description: {
      en: "Velvety black with a bright red abdomen. A hardy, affordable terrestrial that loves to burrow and rearrange its home.",
      fr: "Noire veloutée à l'abdomen rouge vif. Une terrestre robuste et abordable qui adore creuser et réaménager son habitat.",
    },
    careGuide: "beginner-setup",
    arrived: "2026-04-15",
  },
  {
    id: "lparahybana",
    slug: "lasiodora-parahybana-salmon-pink-birdeater",
    scientific: "Lasiodora parahybana",
    common: { en: "Salmon Pink Birdeater", fr: "Mangeuse d'oiseaux rose saumon" },
    genus: "Lasiodora",
    experience: "intermediate",
    type: "terrestrial",
    temperament: "defensive",
    rating: 4.7,
    reviews: 66,
    hue: 350,
    accent: "#9a4a55",
    sizes: [
      sz("s", 25, 18),
      sz("j", 55, 9),
      sz("u", 110, 4),
    ],
    adultSize: { en: "20–25 cm", fr: "20–25 cm" },
    growth: { en: "Fast", fr: "Rapide" },
    origin: { en: "Brazil", fr: "Brésil" },
    lifespan: { en: "12–15 years (F)", fr: "12–15 ans (F)" },
    humidity: "65–75%",
    temperature: "24–28°C",
    enclosure: { en: "Terrestrial, large floor space", fr: "Terrestre, grande surface au sol" },
    diet: { en: "Large crickets, roaches", fr: "Gros grillons, blattes" },
    description: {
      en: "One of the largest tarantulas in the world and a voracious eater. Fast-growing and dramatic — best for keepers comfortable with urticating hairs and size.",
      fr: "L'une des plus grandes mygales au monde et une mangeuse vorace. À croissance rapide et spectaculaire — idéale pour qui est à l'aise avec sa taille et ses poils urticants.",
    },
    careGuide: "feeding-molting",
    arrived: "2026-03-28",
  },
  {
    id: "tstirmi",
    slug: "theraphosa-stirmi-burgundy-goliath-birdeater",
    scientific: "Theraphosa stirmi",
    common: { en: "Burgundy Goliath Birdeater", fr: "Mangeuse d'oiseaux Goliath bourgogne" },
    genus: "Theraphosa",
    experience: "advanced",
    type: "terrestrial",
    temperament: "defensive",
    rating: 4.8,
    reviews: 38,
    hue: 18,
    accent: "#7a3526",
    sizes: [
      sz("s", 120, 4),
      sz("j", 220, 2),
    ],
    adultSize: { en: "25–28 cm", fr: "25–28 cm" },
    growth: { en: "Fast", fr: "Rapide" },
    origin: { en: "Guyana, Brazil", fr: "Guyana, Brésil" },
    lifespan: { en: "15–20 years (F)", fr: "15–20 ans (F)" },
    humidity: "75–85%",
    temperature: "25–29°C",
    enclosure: { en: "Terrestrial, deep moist substrate", fr: "Terrestre, substrat humide profond" },
    diet: { en: "Large roaches", fr: "Grosses blattes" },
    description: {
      en: "A true giant — heavyweight, humidity-loving and not for the faint of heart. Potent urticating hairs and serious size make this an advanced keeper's prize.",
      fr: "Un vrai géant — massif, amateur d'humidité et pas pour les âmes sensibles. Des poils urticants puissants et une taille sérieuse en font le trophée de l'éleveur avancé.",
    },
    careGuide: "advanced-husbandry",
    arrived: "2026-05-02",
  },
  {
    id: "pmurinus",
    slug: "pterinochilus-murinus-orange-baboon",
    scientific: "Pterinochilus murinus",
    common: { en: "Orange Baboon (OBT)", fr: "Babouin orange (OBT)" },
    genus: "Pterinochilus",
    experience: "advanced",
    type: "fossorial",
    temperament: "defensive",
    rating: 4.7,
    reviews: 91,
    hue: 28,
    accent: "#d2761f",
    sizes: [
      sz("s", 20, 22),
      sz("j", 45, 10),
    ],
    adultSize: { en: "12–15 cm", fr: "12–15 cm" },
    growth: { en: "Fast", fr: "Rapide" },
    origin: { en: "East Africa", fr: "Afrique de l'Est" },
    lifespan: { en: "12–15 years (F)", fr: "12–15 ans (F)" },
    humidity: "55–65%",
    temperature: "24–28°C",
    enclosure: { en: "Fossorial/heavy webbing, secure lid", fr: "Fouisseuse/toile dense, couvercle sûr" },
    diet: { en: "Crickets, roaches", fr: "Grillons, blattes" },
    description: {
      en: "Infamous, fast and unapologetically defensive — the 'Orange Bitey Thing'. A stunning old-world spider for experienced keepers who respect speed and a potent bite.",
      fr: "Célèbre, rapide et résolument défensive — l'« Orange Bitey Thing ». Une superbe mygale de l'Ancien Monde pour éleveurs aguerris qui respectent sa vitesse et sa morsure.",
    },
    careGuide: "advanced-husbandry",
    arrived: "2026-05-08",
  },
  {
    id: "mbalfouri",
    slug: "monocentropus-balfouri-socotra-island-blue",
    scientific: "Monocentropus balfouri",
    common: { en: "Socotra Island Blue Baboon", fr: "Babouin bleu de Socotra" },
    genus: "Monocentropus",
    experience: "intermediate",
    type: "fossorial",
    temperament: "defensive",
    newArrival: true,
    rating: 4.9,
    reviews: 44,
    hue: 205,
    accent: "#5a7fa8",
    sizes: [
      sz("s", 60, 9),
      sz("j", 120, 4),
    ],
    adultSize: { en: "11–13 cm", fr: "11–13 cm" },
    growth: { en: "Medium", fr: "Moyenne" },
    origin: { en: "Socotra Island, Yemen", fr: "Île de Socotra, Yémen" },
    lifespan: { en: "12–15 years (F)", fr: "12–15 ans (F)" },
    humidity: "55–65%",
    temperature: "24–28°C",
    enclosure: { en: "Fossorial, webs heavily, communal-capable", fr: "Fouisseuse, tisse beaucoup, possible en communauté" },
    diet: { en: "Crickets, roaches", fr: "Grillons, blattes" },
    description: {
      en: "Soft blue-grey with golden carapace and one of the few genuinely communal tarantulas. Faster and defensive, but a fascinating, beautiful old-world species.",
      fr: "Gris-bleu doux au céphalothorax doré, et l'une des rares mygales réellement grégaires. Plus rapide et défensive, mais une espèce de l'Ancien Monde fascinante et magnifique.",
    },
    careGuide: "advanced-husbandry",
    arrived: "2026-05-30",
  },
  {
    id: "pmetallica",
    slug: "poecilotheria-metallica-gooty-sapphire",
    scientific: "Poecilotheria metallica",
    common: { en: "Gooty Sapphire Ornamental", fr: "Ornementale saphir de Gooty" },
    genus: "Poecilotheria",
    experience: "advanced",
    type: "arboreal",
    temperament: "defensive",
    featured: true,
    rating: 5.0,
    reviews: 57,
    hue: 210,
    accent: "#3f6fd1",
    sizes: [
      sz("s", 90, 6),
      sz("j", 180, 3),
    ],
    adultSize: { en: "15–18 cm", fr: "15–18 cm" },
    growth: { en: "Medium-fast", fr: "Moyenne-rapide" },
    origin: { en: "Andhra Pradesh, India", fr: "Andhra Pradesh, Inde" },
    lifespan: { en: "11–12 years (F)", fr: "11–12 ans (F)" },
    humidity: "70–80%",
    temperature: "24–28°C",
    enclosure: { en: "Arboreal, vertical, secure, cross-ventilated", fr: "Arboricole, vertical, sécurisé, ventilé" },
    diet: { en: "Crickets, flying insects", fr: "Grillons, insectes volants" },
    description: {
      en: "Possibly the most beautiful tarantula alive — electric blue with intricate fractal patterning. Fast, defensive and venom you respect: a grail species for advanced keepers.",
      fr: "Peut-être la plus belle mygale vivante — bleu électrique aux motifs fractals complexes. Rapide, défensive et au venin à respecter : une espèce-graal pour éleveurs avancés.",
    },
    careGuide: "advanced-husbandry",
    arrived: "2026-05-29",
  },
  {
    id: "pirminia",
    slug: "psalmopoeus-irminia-venezuelan-suntiger",
    scientific: "Psalmopoeus irminia",
    common: { en: "Venezuelan Suntiger", fr: "Tigre solaire du Venezuela" },
    genus: "Psalmopoeus",
    experience: "intermediate",
    type: "arboreal",
    temperament: "skittish",
    rating: 4.7,
    reviews: 52,
    hue: 32,
    accent: "#c47a1e",
    sizes: [
      sz("s", 30, 11),
      sz("j", 65, 6),
    ],
    adultSize: { en: "13–15 cm", fr: "13–15 cm" },
    growth: { en: "Fast", fr: "Rapide" },
    origin: { en: "Venezuela", fr: "Venezuela" },
    lifespan: { en: "10–12 years (F)", fr: "10–12 ans (F)" },
    humidity: "70–80%",
    temperature: "24–28°C",
    enclosure: { en: "Arboreal, vertical with hide", fr: "Arboricole, vertical avec cachette" },
    diet: { en: "Crickets, flying insects", fr: "Grillons, insectes volants" },
    description: {
      en: "Jet black with vivid orange tiger markings on the legs. A fast, secretive arboreal that's a perfect stepping-stone toward old-world species.",
      fr: "Noir de jais aux marques tigrées orange vif sur les pattes. Une arboricole rapide et discrète, parfaite étape vers les espèces de l'Ancien Monde.",
    },
    careGuide: "arboreal-setup",
    arrived: "2026-04-10",
  },
  {
    id: "celegans",
    slug: "cyriocosmus-elegans-trinidad-dwarf",
    scientific: "Cyriocosmus elegans",
    common: { en: "Trinidad Dwarf", fr: "Naine de Trinité" },
    genus: "Cyriocosmus",
    experience: "beginner",
    type: "terrestrial",
    temperament: "skittish",
    rating: 4.6,
    reviews: 33,
    hue: 45,
    accent: "#b89030",
    sizes: [
      sz("s", 25, 15),
      sz("j", 45, 8),
    ],
    adultSize: { en: "4–6 cm", fr: "4–6 cm" },
    growth: { en: "Medium", fr: "Moyenne" },
    origin: { en: "Trinidad, Venezuela", fr: "Trinité, Venezuela" },
    lifespan: { en: "6–8 years (F)", fr: "6–8 ans (F)" },
    humidity: "65–75%",
    temperature: "23–27°C",
    enclosure: { en: "Small terrestrial, deep substrate", fr: "Petite terrestre, substrat profond" },
    diet: { en: "Small crickets, flightless flies", fr: "Petits grillons, mouches aptères" },
    description: {
      en: "A tiny jewel with a heart-shaped golden abdomen marking. Perfect for keepers short on space who still want striking colour and personality.",
      fr: "Un minuscule joyau à la marque dorée en forme de cœur sur l'abdomen. Parfaite pour qui manque d'espace mais veut couleur et caractère.",
    },
    careGuide: "beginner-setup",
    arrived: "2026-04-05",
  },
  {
    id: "dpentaloris",
    slug: "davus-pentaloris-guatemalan-tiger-rump",
    scientific: "Davus pentaloris",
    common: { en: "Guatemalan Tiger Rump", fr: "Croupe tigrée du Guatemala" },
    genus: "Davus",
    experience: "intermediate",
    type: "terrestrial",
    temperament: "skittish",
    rating: 4.7,
    reviews: 41,
    hue: 8,
    accent: "#a23f2c",
    sizes: [
      sz("s", 25, 12),
      sz("j", 50, 6),
    ],
    adultSize: { en: "9–11 cm", fr: "9–11 cm" },
    growth: { en: "Medium", fr: "Moyenne" },
    origin: { en: "Guatemala, Mexico", fr: "Guatemala, Mexique" },
    lifespan: { en: "10–12 years (F)", fr: "10–12 ans (F)" },
    humidity: "65–75%",
    temperature: "23–27°C",
    enclosure: { en: "Terrestrial, webs a lot", fr: "Terrestre, tisse beaucoup" },
    diet: { en: "Crickets, roaches", fr: "Grillons, blattes" },
    description: {
      en: "Beautiful tiger-striped abdomen and a busy, webby lifestyle. Fast but rewarding — a colourful intermediate that's always on display.",
      fr: "Magnifique abdomen rayé tigré et un mode de vie actif et tissé. Rapide mais gratifiante — une intermédiaire colorée toujours en vue.",
    },
    careGuide: "feeding-molting",
    arrived: "2026-04-18",
  },
  {
    id: "hsp-colombia",
    slug: "hapalopus-sp-colombia-pumpkin-patch",
    scientific: "Hapalopus sp. Colombia",
    common: { en: "Pumpkin Patch", fr: "Champ de citrouilles" },
    genus: "Hapalopus",
    experience: "beginner",
    type: "terrestrial",
    temperament: "skittish",
    newArrival: true,
    rating: 4.8,
    reviews: 47,
    hue: 26,
    accent: "#cf7a23",
    sizes: [
      sz("s", 30, 14),
      sz("j", 55, 7),
    ],
    adultSize: { en: "5–7 cm", fr: "5–7 cm" },
    growth: { en: "Fast", fr: "Rapide" },
    origin: { en: "Colombia", fr: "Colombie" },
    lifespan: { en: "6–9 years (F)", fr: "6–9 ans (F)" },
    humidity: "65–75%",
    temperature: "23–27°C",
    enclosure: { en: "Small terrestrial, deep substrate, webs", fr: "Petite terrestre, substrat profond, tisse" },
    diet: { en: "Small crickets, flightless flies", fr: "Petits grillons, mouches aptères" },
    description: {
      en: "A vivid orange-and-black dwarf with a jack-o'-lantern abdomen pattern. Fast-growing, heavy webber and packed with personality despite its small size.",
      fr: "Une naine orange et noire au motif d'abdomen évoquant une citrouille d'Halloween. Croissance rapide, grande tisseuse et pleine de caractère malgré sa petite taille.",
    },
    careGuide: "beginner-setup",
    arrived: "2026-05-31",
  },
];

export function getProduct(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function relatedProducts(p: Product, count = 3): Product[] {
  return PRODUCTS.filter(
    (o) => o.id !== p.id && (o.genus === p.genus || o.experience === p.experience)
  ).slice(0, count);
}

export const GENERA = Array.from(new Set(PRODUCTS.map((p) => p.genus))).sort();
